(() => {
  const STORAGE_KEY = "speedLogisticsPrototype_v1";
  const stages = [
    {label:"Order accepted", location:"Booking centre", note:"Order confirmed and tracking ID generated."},
    {label:"Picked up", location:"Origin city", note:"Cargo picked up from sender."},
    {label:"At origin warehouse", location:"Origin warehouse", note:"Cargo scanned into the origin facility."},
    {label:"Ready for dispatch", location:"Origin warehouse", note:"Shipment sorted and ready for dispatch."},
    {label:"In transit", location:"En route to destination", note:"Shipment departed the origin hub."},
    {label:"At destination hub", location:"Destination hub", note:"Arrival recorded at the destination hub."},
    {label:"Out for delivery", location:"Delivery route", note:"Delivery partner has taken custody of the shipment."},
    {label:"Delivered", location:"Recipient address", note:"Delivery marked complete. Proof of delivery is simulated."}
  ];
  const defaults = [
    {id:"SL-2026-1042",recipient:"Olivia Carter",sender:"Aarav Mehta",origin:"Delhi, India",destination:"London, UK",contents:"Electronics · 2 cartons",weight:"18.5 kg",service:"International Express",statusIndex:2,warehouse:"Zone B · Rack 12 · Bin 04",flight:"SL 208 (demo)",eta:"2026-10-09T14:00",agent:"Daniel Brooks",agentPhone:"+44 7700 900123",lastUpdate:"2026-10-08T10:15",events:[{stage:"Order Accepted",location:"Delhi Booking Centre",note:"Order confirmed and tracking ID generated.",time:"2026-10-08T08:40"},{stage:"Picked Up",location:"Delhi, India",note:"Cargo picked up from sender.",time:"2026-10-08T09:10"},{stage:"At Origin Warehouse",location:"Delhi Origin Warehouse",note:"Cargo scanned into the warehouse.",time:"2026-10-08T10:15"}]},
    {id:"SL-2026-1043",recipient:"Noah Williams",sender:"Mira Sharma",origin:"Noida, India",destination:"Mumbai, India",contents:"Documents · 1 pack",weight:"0.8 kg",service:"Domestic Priority",statusIndex:5,warehouse:"Mumbai Hub · Sort Area 2",flight:"SL 415 (demo)",eta:"2026-10-08T18:00",agent:"Priya Singh",agentPhone:"+91 90000 12345",lastUpdate:"2026-10-08T14:10",events:[{stage:"Order Accepted",location:"Noida Booking Centre",note:"Order confirmed and tracking ID generated.",time:"2026-10-08T08:10"},{stage:"Picked Up",location:"Noida, India",note:"Cargo picked up from sender.",time:"2026-10-08T08:45"},{stage:"At Origin Warehouse",location:"Noida Origin Warehouse",note:"Cargo received and scanned.",time:"2026-10-08T09:15"},{stage:"Ready for Dispatch",location:"Noida Origin Warehouse · Zone A",note:"Sorted and loaded for line-haul transport.",time:"2026-10-08T10:30"},{stage:"In Transit",location:"En route to Mumbai",note:"Shipment departed Noida hub.",time:"2026-10-08T11:00"},{stage:"At Destination Hub",location:"Mumbai Destination Hub",note:"Arrival scan recorded at destination hub.",time:"2026-10-08T14:10"}]},
    {id:"SL-2026-1044",recipient:"Ananya Rao",sender:"Kabir Malhotra",origin:"Jaipur, India",destination:"Bengaluru, India",contents:"Apparel · 3 boxes",weight:"6.4 kg",service:"Domestic Standard",statusIndex:1,warehouse:"Jaipur Pickup Zone",flight:"Not assigned",eta:"2026-10-10T18:00",agent:"Not assigned",agentPhone:"",lastUpdate:"2026-10-08T09:20",events:[{stage:"Order Accepted",location:"Jaipur Booking Centre",note:"Order confirmed and tracking ID generated.",time:"2026-10-08T08:30"},{stage:"Picked Up",location:"Jaipur, India",note:"Package collected from the sender.",time:"2026-10-08T09:20"}]},
    {id:"SL-2026-1045",recipient:"Arjun Kapoor",sender:"Isha Verma",origin:"Pune, India",destination:"Hyderabad, India",contents:"Computer accessories · 1 carton",weight:"4.2 kg",service:"Domestic Priority",statusIndex:4,warehouse:"Pune Line-haul Hub",flight:"SL 327 (demo)",eta:"2026-10-09T11:00",agent:"Not assigned",agentPhone:"",lastUpdate:"2026-10-08T12:05",events:[{stage:"Order Accepted",location:"Pune Booking Centre",note:"Order confirmed and tracking ID generated.",time:"2026-10-08T08:00"},{stage:"Picked Up",location:"Pune, India",note:"Package collected from sender.",time:"2026-10-08T08:35"},{stage:"At Origin Warehouse",location:"Pune Origin Warehouse",note:"Package scanned into the origin facility.",time:"2026-10-08T09:05"},{stage:"Ready for Dispatch",location:"Pune Origin Warehouse · Bay 3",note:"Package sorted and loaded for transport.",time:"2026-10-08T10:10"},{stage:"In Transit",location:"En route to Hyderabad",note:"Shipment departed Pune hub.",time:"2026-10-08T12:05"}]},
    {id:"SL-2026-1046",recipient:"Meera Nair",sender:"Rohan Sethi",origin:"Gurugram, India",destination:"Chennai, India",contents:"Business documents · 1 secure pack",weight:"1.1 kg",service:"Domestic Priority",statusIndex:6,warehouse:"Chennai Destination Hub · Dispatch Bay",flight:"SL 552 (demo)",eta:"2026-10-08T17:00",agent:"Karthik Raman",agentPhone:"+91 90000 24680",lastUpdate:"2026-10-08T15:40",events:[{stage:"Order Accepted",location:"Gurugram Booking Centre",note:"Order confirmed and tracking ID generated.",time:"2026-10-07T15:10"},{stage:"Picked Up",location:"Gurugram, India",note:"Package collected from sender.",time:"2026-10-07T16:00"},{stage:"At Origin Warehouse",location:"Gurugram Origin Warehouse",note:"Package scanned at origin facility.",time:"2026-10-07T17:10"},{stage:"Ready for Dispatch",location:"Gurugram Origin Warehouse · Bay 2",note:"Package cleared for dispatch.",time:"2026-10-07T18:00"},{stage:"In Transit",location:"En route to Chennai",note:"Shipment departed the origin hub.",time:"2026-10-07T21:15"},{stage:"At Destination Hub",location:"Chennai Destination Hub",note:"Shipment received at destination hub.",time:"2026-10-08T06:20"},{stage:"Out for Delivery",location:"Chennai Delivery Route",note:"Delivery partner has taken custody of the shipment.",time:"2026-10-08T15:40"}]}
  ];
  const $ = (id) => document.getElementById(id);
  const esc = (v="") => String(v).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  function shipments(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");if(Array.isArray(value)&&value.length){const ids=new Set(value.map(s=>s.id));const merged=[...value,...defaults.filter(s=>!ids.has(s.id))];try{localStorage.setItem(STORAGE_KEY,JSON.stringify(merged));}catch(e){}return merged;}}catch(e){}return defaults;}
  function fmt(value){if(!value)return "Not available";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true});}
  function status(s){return s.statusIndex===7?"green":s.statusIndex>=4?"blue":s.statusIndex<=1?"gray":"amber";}
  function track(id){
    const s=shipments().find(x=>String(x.id).toLowerCase()===String(id||"").trim().toLowerCase());
    const out=$("publicTrackingResult");
    if(!s){out.innerHTML=`<div class="card tracking-empty"><div class="empty"><div class="empty-icon">⌕</div><strong>No shipment found</strong><p>Check the tracking ID and try again.</p></div></div>`;return;}
    $("publicTrackingSearch").value=s.id;
    const idx=Math.max(0,Math.min(Number(s.statusIndex)||0,7));
    const location=(idx===2||idx===3)&&s.warehouse?s.warehouse:idx===4&&s.flight?`In transit · ${s.flight}`:idx===6&&s.agent?`With ${s.agent} · ${s.destination}`:(stages[idx].location);
    const eventByStage=new Map((s.events||[]).map(e=>[String(e.stage).toLowerCase(),e]));
    const progress=Math.round((idx/7)*100);
    out.innerHTML=`<div class="tracking-result-grid">
      <section class="card"><div class="shipment-title"><div><div class="eyebrow">TRACKING ID</div><h2>${esc(s.id)}</h2><div class="small muted">Recipient: ${esc(s.recipient||"Not provided")}</div></div><span class="status ${status(s)}"><i class="pill-dot"></i>${esc(stages[idx].label)}</span></div>
      <div class="tracking-route"><div><div class="city">${esc((s.origin||"Origin").split(",")[0])}</div><div class="code">${esc(s.origin||"Origin not provided")}</div></div><div class="route-mid">↗<span></span></div><div style="text-align:right"><div class="city">${esc((s.destination||"Destination").split(",")[0])}</div><div class="code">${esc(s.destination||"Destination not provided")}</div></div></div>
      <div class="metrics"><div class="metric"><div class="label">ESTIMATED DELIVERY</div><div class="value">${idx===7?"Delivered":esc(s.eta?fmt(s.eta):"Pending update")}</div></div><div class="metric"><div class="label">LAST CONFIRMED LOCATION</div><div class="value">${esc(location)}</div></div><div class="metric"><div class="label">LAST UPDATE</div><div class="value">${esc(fmt(s.lastUpdate))}</div></div></div>
      ${idx>=6?`<div class="agent-card"><div class="avatar">${esc((s.agent||"D").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase())}</div><div><div class="eyebrow">DELIVERY AGENT</div><strong style="display:block;margin-top:4px">${esc(s.agent&&s.agent!=="Not assigned"?s.agent:"Agent details not available")}</strong><div class="small muted" style="margin-top:5px">${s.agentPhone?`Contact: ${esc(s.agentPhone)}`:"Contact number not provided"}</div></div></div>`:""}
      <div class="progress-track"><div class="progress-fill" style="width:${progress}%"></div></div><div class="small muted" style="margin-top:7px">${progress}% of the shipment journey recorded</div>
      </section>
      <section class="card"><div class="section-head"><div><h2>Shipment journey</h2><p>Recorded checkpoints and current progress.</p></div></div><div class="timeline">${stages.map((stage,i)=>{const e=eventByStage.get(stage.label.toLowerCase())||eventByStage.get(stage.label.replace(/^./,c=>c.toUpperCase()).toLowerCase());const done=i<idx,current=i===idx;return `<div class="event ${done?"done":""} ${current?"current":"future"}"><div class="event-dot"></div><div class="event-body"><h4>${esc(stage.label)}</h4><p>${esc(e?.location||(i===idx?location:stage.location))}</p><div class="small muted">${e?.time?esc(fmt(e.time)):current?"Current status":"Awaiting checkpoint"}</div>${e?.note?`<p class="event-note">${esc(e.note)}</p>`:""}</div></div>`}).join("")}</div></section>
    </div>`;
  }
  $("publicTrackForm").addEventListener("submit",e=>{e.preventDefault();track($("publicTrackingSearch").value);});
  document.querySelectorAll("[data-public-track]").forEach(b=>b.addEventListener("click",()=>track(b.dataset.publicTrack)));
  const initial=new URLSearchParams(location.search).get("id");if(initial)track(initial);
})();
